spring.application.name=mvp_1
spring.r2dbc.url=${DB_URL}
spring.r2dbc.username=${DB_UNAME}
spring.r2dbc.password=${DB_PASS}
spring.sql.init.mode=always

spring.webflux.multipart.max-in-memory-size:10MB
spring.main.web-application-type=reactive

server.address=0.0.0.0
server.port=${PORT:10000}

r2.accessKey=${R2_ACCESS_KEY}
r2.secretKey=${R2_SECRET_KEY}
r2.endpoint=${R2_ENDPOINT}
r2.bucket=letschat-media

firebase.config=${FIREBASE_CONFIG}