spring.application.name=mvp_1
spring.r2dbc.url=r2dbc:postgresql://localhost:5432/letschat_mvp_db
spring.r2dbc.username=postgres
spring.r2dbc.password=yoke1234
spring.sql.init.mode=always

spring.webflux.multipart.max-in-memory-size:10MB
spring.main.web-application-type=reactive

server.address=0.0.0.0
server.port=8080

r2.accessKey=1e65b5bc0967548ed673f96599ac02de
r2.secretKey=52d0a2a5693a04ce4fa12b85ca6c9235f9f3f1354070453821462c19ccf88d1f
r2.endpoint=https://6333a79c55b347b44afe2e0f4094b0c4.r2.cloudflarestorage.com
r2.bucket=letschat-media